### PR TITLE
CircleCI project setup - Build & Run

### PR DESCRIPTION
**Pull request by Fishbowler**
Covers building Openfire in CircleCI
~PR to follow that performs running.~ Also runs Openfire reusing components from Github.

### CODE REVIEW

**Comment by guusdk** [comment]
Should we skip running the unit tests during build? Generally speaking, it's obviously preferable to run these tests, but for the purpose of testing the _integration_ tests, they're not needed. By disabling them (`-Dmaven.test.skip=true`), the build time will improve dramatically.

**Comment by Fishbowler** [comment]
Done.

Adding caching saved a bit. Skipping unit tests did better.

image

**Comment by guusdk** [comment]
Nice! Should we explicitly _stop_ the server, at the end of the flow? I'm guessing CircleCI will eventually clean things up, but it would be tidy to make sure things are shut down properly. Like the start script, we have a stop script in the Github Action that may be usable for that.

**Comment by Fishbowler** [comment]
I'm not convinced that it's worth the (albeit small) complexity. Timestamps show that it's being cleaned up promptly after the last command runs.

Hmmm. I'm gonna ask someone I know at Circle about what they'd rather we do 🤔

**Comment by Fishbowler** [comment]
* Switched to downloading and running a tar rather than building from source. Some reasonable time savings - some "build" runs down to 9s!
* Fixed Openfire halting in the background

**Comment by Fishbowler** [comment]
Switched source for notices on where to find the source

**Pull request closed without merging**
